### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by manikandarajzma** [sdnewhop/grinder#13]
(grindervenv) root@osboxes:~/grinder# ./grinder.py  -sk SK -ci cenkey -cs censecret -u -q queries.json -cu -cp -cm 555 -nm -r 
  .,-:::::/ :::::::..   ::::::.    :::.:::::::-.  .,:::::: :::::::..   
,;;-'````'  ;;;;``;;;;  ;;;`;;;;,  `;;; ;;,   `';,;;;;'''' ;;;;``;;;;  
[[[   [[[[[[/[[[,/[[['  [[[  [[[[[. '[[ `[[     [[ [[cccc   [[[,/[[['  
"$$c.    "$$ $$$$$$c    $$$  $$$ "Y$c$$  $$,    $$ $$""""   $$$$$$c    
 `Y8bo,,,o88o888b "88bo,888  888    Y88  888_,o8P' 888oo,__ 888b "88bo,
   `'YMUP"YMMMMMM   "W" MMM  MMM     YM  MMMMP"`   """"YUMMMMMMM   "W" 

Shodan API key: ***
Censys API ID: ***
Censys API SECRET: ***
File with queries: queries.json
Unexpected error occured at batch search method.

**Comment by manmolecular** [comment]
Hello, @manikandarajzma.

Thanks for your issue - I was able to reproduce the problem and currently fix it with new features from develop branch. Problem was associated with new filtering methods by vendors and by confidence levels which I am currently working on, in case of empty vendor filters: 12f4796eb205dd754802af12a97d3ea8b2ebeb15

You can pull the latest updates from the master branch into your local repository copy and check that everything is working properly now. If you have any problems or questions about Grinder - feel free to tell about it here or you can create another issue related to your problem.

I was able now to run it properly as you show it in your example:
```bash
./grinder.py -sk YOUR_SHODAN_KEY -ci YOUR_CENSYS_KEY -cs YOUR_CENSYS_SECRET -u -q queries.json -cu -cp -cm 555 -nm -r
```
