### ISSUE TITLE
Automated code review for grinder

### ISSUE THREAD

**Issue by P-ignatovich** [sdnewhop/grinder#96]
Hi!
I am a member of the team developing **monocodus** — a service that performs automatic code review of GitHub pull requests to help organizations ensure a high quality of code.
We’ve developed some useful features to the moment, and now we’re looking for early users and feedback to find out what we should improve and which features the community needs the most.
We ran monocodus on a pre-created fork of your repo on GitHub https://github.com/monocodus-demonstrations/grinder/pulls, and it found some formatting issues (according to AutoPEP8) and some potentially overcomplicated functions. 
I hope that this information will be useful to you and would be happy to receive any feedback here on my email pavel@monocodus.com
If you want to try our service, feel free to follow the link: https://www.monocodus.com
The service is entirely free of charge for open source projects. Hope you’ ll like it :)

**Comment by GraylockInc** [comment]
Before suggesting security concerns with others maybe you should run Monocodus against yourselves, there are numerous JS files with security issues on your own website.
